module.exports = [
     "Home Win",
     "Away Win",
     "Draw",
     "BTTS",
     "BTTS No",
     "Over 1.5",
     "Over 2.5",
     "Over 3.5",
     "Under 1.5",
     "Under 2.5",
     "Under 3.5",
     "TotalGoal 2-3",
     "Home DNB",
     "Away DNB",
     "AH Home +1",
     "AH Away +1",
     "AH Home -1",
     "AH Away -1",
     "AH Home +1.5",
     "AH Away +1.5",
     "AH Home -1.5",
     "AH Away -1.5"
]